apiVersion: v1
kind: Service
metadata:
  name: multicont-svc1 
spec:
  ports:
  - port: 80
    name: http 
    targetPort: http
  - port: 443
    name: https
    targetPort: https
  selector:
    app: kubia   


